### ISSUE TITLE
Missplaced popup

### ISSUE THREAD

**Issue by Abbe98** [pelagios/recogito-text-js#27] opened 2019-12-14 08:11 UTC
If the text to be annotated is higher then the web browser view port the Recogito popup will be rendered in the wrong vertically location and cause the browser scroll to that location.

Create a annotation in the following example:
[reproducable-example.html.txt](https://github.com/pelagios/recogito-text-js/files/3963592/tmp.txt)

Only tested in Firefox.

**Comment by rsimon** [comment] 2019-12-14 09:20
Thanks for reporting - I can reproduce it (and in fact noticed it yesterday myself - while giving a live demo to someone... as usual.) Will look into it!

**Comment by rsimon** [comment] 2019-12-14 15:26
Looks like this was actually fixed on master already, but the live demo (and the built code that the live demo uses) wasn't up to date. I updated the code on the live demo, and it looks like this is now working. Do let me know if you can confirm, or whether it's still broken for you.

**Closed** 2020-01-14 10:47 UTC
